### ISSUE TITLE
AttributeError: module 'airflow.settings' has no attribute 'engine'

### ISSUE THREAD

**Issue by ciusji** [GuinsooLab/sheenflow#13]
Can not  init db env in dev mode: 

```bash
Traceback (most recent call last):
  File "/Users/admin/Anaconda3/envs/sheenflow/bin/sheenflow", line 8, in <module>
    sys.exit(main())
  File "/Users/admin/Git/Public/sheenflow/airflow/__main__.py", line 38, in main
    args.func(args)
  File "/Users/admin/Git/Public/sheenflow/airflow/cli/cli_parser.py", line 51, in command
    return func(*args, **kwargs)
  File "/Users/admin/Git/Public/sheenflow/airflow/cli/commands/db_command.py", line 34, in initdb
    print("DB: " + repr(settings.engine.url))
AttributeError: module 'airflow.settings' has no attribute 'engine'
```

**Comment by ciusji** [comment]
Please remove `sheenflow-airflow package`, this is a local dev-test.
